#!/bin/bash
# binder post build script
set -ex

(cd docs && make html)

pip uninstall -y -r docs_requirements.txt

ls -la

mv docs/build/html/notebooks .
mv examples/titanic_example/assets notebooks/auto_examples/titanic_example
mv substrafl_examples/strategies_examples/assets notebooks/substrafl_doc/examples/strategies_examples

shopt -s extglob
rm -rf !(notebooks)
