name: Documentation examples subprocess mode

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "12 3 * * 2-6" # every Tuesday to Saturday at 3:12 AM
jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Clone substra-tools
        uses: actions/checkout@v3
        with:
          repository: substra/substra-tools
          path: substra-tools
          ref: main

      - name: Clone substra
        uses: actions/checkout@v3
        with:
          repository: substra/substra
          path: substra
          ref: main

      - name: Clone substrafl
        uses: actions/checkout@v3
        with:
          repository: substra/substrafl
          path: substrafl
          ref: main

      - name: Install substra, substra-tools and substrafl
        run: |
          pip install -e ./substrafl
          pip install -e ./substra
          pip install -e ./substra-tools

      - name: Run examples
        run: |
          python -u ./run-examples.py \
            --write-summary-to-file ./.slack_message
            --docker-mode True

      - if: always() && github.event_name == 'schedule'
        name: Send Slack report
        run: |
          ./send-slack-report.py '${{ secrets.SLACK_WEBHOOK }}' .slack_message \
          --title 'Documentation examples subprocess mode' \
          --status '${{ job.status }}' \
          --link 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
