name: Documentation examples - subprocess
on:
  pull_request:
    paths:
     - "docs/source/examples/**"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pr-validation:
    name: test-${{ matrix.os }}-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          path: substra-documentation

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Free disk space
        run: |
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout substra-tools on main
        uses: actions/checkout@v4
        with:
          repository: substra/substra-tools
          path: substratools

      - name: Checkout substra on main
        uses: actions/checkout@v4
        with:
          repository: substra/substra
          path: substra

      - name: Checkout substrafl on main
        uses: actions/checkout@v4
        with:
          repository: substra/substrafl
          path: substrafl

      - name: Install package
        run: |
          pip install --upgrade pip
          pip install --upgrade -e substrafl
          pip install --upgrade -e substra
          pip install --upgrade -e substratools

      - name: Install examples dependencies
        run: |
          cd substra-documentation
          make install-examples-dependencies

      - name: Run examples
        env:
          SUBSTRA_FORCE_EDITABLE_MODE: True
        run: |
          cd substra-documentation
          make examples
